### ISSUE TITLE
Vertical scrollbar breaks handy-scroll

### ISSUE THREAD

**Issue by Lawok** [Amphiluke/handy-scroll#2]
![handy-scroll-bug](https://user-images.githubusercontent.com/9695821/47662172-1bf51980-dba3-11e8-9dc6-c0c05ae6fc45.gif)

Tested on latest Chrome (70.0.3538.77)

When the container has also a vertical scrollbar and you try to scroll to the right with the handy-scroll, it does not scroll till the end, right most position. Using "the real scroll" at the bottom works, or using shift + mouse wheel.

Can be reproduced on the live demo page, by limiting the container height so that vertical scrollbar appears.

**Comment by Amphiluke** [comment]
Thank you @Lawok for reporting! Fixed in [v1.0.2](https://github.com/Amphiluke/handy-scroll/releases/tag/v1.0.2). 
_Note:_ If the container acquires or loses the vertical scrollbar _dynamically_, then please don’t forget to invoke the [update](https://github.com/Amphiluke/handy-scroll#updating-scrollbar) method to make the widget recalculate its size accordingly.
